spec:
  replicas: 1
  imagePullSecrets: ""

config:
  reverseProxy: 
    {
      "Routes": {
        "route1" : {
          "ClusterId": "cms-usermanagement",
          "Match": {
            "Path": "/usermanagement/{**catch-all}"
          },
          "Transforms": [{ "PathPattern": "{**catch-all}" }]
        },
        "route2" : {
          "ClusterId": "cms-showmanagement",
          "Match": {
            "Path": "/showmanagement/{**catch-all}"
          },
          "Transforms": [{ "PathPattern": "{**catch-all}" }]
        },
        "route3": {
          "ClusterId": "cms-imageassetmanagement",
          "Match": {
            "Path": "/imageassetmanagement/{**catch-all}"
          },
          "Transforms": [{ "PathPattern": "{**catch-all}" }]
        },
        "route4": {
          "ClusterId": "cms-programmanagement",
          "Match": {
            "Path": "/programmanagement/{**catch-all}"
          },
          "Transforms": [{ "PathPattern": "{**catch-all}" }]
        }
      },
      "Clusters": {
        "cms-usermanagement": {
          "Destinations": {
            "Default": {
              "Address": "http://cms-user-management/",
              "Swaggers": [
                {
                  "PrefixPath": "/usermanagement",
                  "Paths": [
                    "swagger/v1/swagger.json"
                  ]
                }
              ]
            }
          }
        },
        "cms-showmanagement": {
          "Destinations": {
            "Default": {
              "Address": "http://cms-show-management/",
              "Swaggers": [
                {
                  "PrefixPath": "/showmanagement",
                  "Paths": [
                    "swagger/v1/swagger.json"
                  ]
                }
              ]
            }
          }
        },
        "cms-imageassetmanagement": {
          "Destinations": {
            "Default": {
              "Address": "http://cms-image-asset-management/",
              "Swaggers": [
                {
                  "PrefixPath": "/imageassetmanagement",
                  "Paths": [
                    "swagger/v1/swagger.json"
                  ]
                }
              ]
            }
          }
        },
        "cms-programmanagement": {
          "Destinations": {
            "Default": {
              "Address": "http://cms-program-management/",
              "Swaggers": [
                {
                  "PrefixPath": "/programmanagement",
                  "Paths": [
                    "swagger/v1/swagger.json"
                  ]
                }
              ]
            }
          }
        }
      }
    }