apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.spec.replicas }}
  selector:
    matchLabels:
      service: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        service: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: tliscr.azurecr.io/cms-api-gateway:{{ .Chart.AppVersion }}
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - mountPath: /app/appsettings.json
            name: config
            subPath: appsettings.json
          ports:
            - containerPort: 8080
              protocol: TCP
      {{ if .Values.spec.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.spec.imagePullSecrets | quote }}
      {{ end }}
      volumes:
      - name: config
        configMap:
          name: {{ .Release.Name }}