apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.spec.replicas }}
  selector:
    matchLabels:
      service: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        service: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: tliscr.azurecr.io/api-gateway:{{ .Chart.AppVersion }}
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - mountPath: /app/appsettings.json
            name: config
            subPath: appsettings.json
          - name: tls
            mountPath: /etc/tls
            readOnly: true
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
            - name: TLS_CERT
              value: /etc/tls/tls.crt
            - name: TLS_KEY
              value: /etc/tls/tls.key
      volumes:
      - name: config
        configMap:
          name: {{ .Release.Name }}
      - name: tls
        secret:
          secretName: www-tls